/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_FLWR_PROTO_PROTO_NODE_PB_H_INCLUDED
#define PB_FLWR_PROTO_PROTO_NODE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _flwr_proto_Node {
    uint64_t node_id;
} flwr_proto_Node;

typedef struct _flwr_proto_NodeInfo {
    uint64_t node_id;
    pb_callback_t owner_aid;
    pb_callback_t owner_name;
    pb_callback_t status;
    pb_callback_t registered_at;
    pb_callback_t last_activated_at;
    pb_callback_t last_deactivated_at;
    pb_callback_t unregistered_at;
    bool has_online_until;
    double online_until;
    double heartbeat_interval;
    pb_callback_t public_key;
} flwr_proto_NodeInfo;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define flwr_proto_Node_init_default             {0}
#define flwr_proto_NodeInfo_init_default         {0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, 0, {{NULL}, NULL}}
#define flwr_proto_Node_init_zero                {0}
#define flwr_proto_NodeInfo_init_zero            {0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, 0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define flwr_proto_Node_node_id_tag              1
#define flwr_proto_NodeInfo_node_id_tag          1
#define flwr_proto_NodeInfo_owner_aid_tag        2
#define flwr_proto_NodeInfo_owner_name_tag       3
#define flwr_proto_NodeInfo_status_tag           4
#define flwr_proto_NodeInfo_registered_at_tag    5
#define flwr_proto_NodeInfo_last_activated_at_tag 6
#define flwr_proto_NodeInfo_last_deactivated_at_tag 7
#define flwr_proto_NodeInfo_unregistered_at_tag  8
#define flwr_proto_NodeInfo_online_until_tag     9
#define flwr_proto_NodeInfo_heartbeat_interval_tag 10
#define flwr_proto_NodeInfo_public_key_tag       11

/* Struct field encoding specification for nanopb */
#define flwr_proto_Node_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   node_id,           1)
#define flwr_proto_Node_CALLBACK NULL
#define flwr_proto_Node_DEFAULT NULL

#define flwr_proto_NodeInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   node_id,           1) \
X(a, CALLBACK, SINGULAR, STRING,   owner_aid,         2) \
X(a, CALLBACK, SINGULAR, STRING,   owner_name,        3) \
X(a, CALLBACK, SINGULAR, STRING,   status,            4) \
X(a, CALLBACK, SINGULAR, STRING,   registered_at,     5) \
X(a, CALLBACK, OPTIONAL, STRING,   last_activated_at,   6) \
X(a, CALLBACK, OPTIONAL, STRING,   last_deactivated_at,   7) \
X(a, CALLBACK, OPTIONAL, STRING,   unregistered_at,   8) \
X(a, STATIC,   OPTIONAL, DOUBLE,   online_until,      9) \
X(a, STATIC,   SINGULAR, DOUBLE,   heartbeat_interval,  10) \
X(a, CALLBACK, SINGULAR, BYTES,    public_key,       11)
#define flwr_proto_NodeInfo_CALLBACK pb_default_field_callback
#define flwr_proto_NodeInfo_DEFAULT NULL

extern const pb_msgdesc_t flwr_proto_Node_msg;
extern const pb_msgdesc_t flwr_proto_NodeInfo_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define flwr_proto_Node_fields &flwr_proto_Node_msg
#define flwr_proto_NodeInfo_fields &flwr_proto_NodeInfo_msg

/* Maximum encoded size of messages (where known) */
/* flwr_proto_NodeInfo_size depends on runtime parameters */
#define FLWR_PROTO_PROTO_NODE_PB_H_MAX_SIZE      flwr_proto_Node_size
#define flwr_proto_Node_size                     11

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
