/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_FLWR_PROTO_PROTO_RECORDDICT_PB_H_INCLUDED
#define PB_FLWR_PROTO_PROTO_RECORDDICT_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _flwr_proto_DoubleList {
    pb_callback_t vals;
} flwr_proto_DoubleList;

typedef struct _flwr_proto_SintList {
    pb_callback_t vals;
} flwr_proto_SintList;

typedef struct _flwr_proto_UintList {
    pb_callback_t vals;
} flwr_proto_UintList;

typedef struct _flwr_proto_BoolList {
    pb_callback_t vals;
} flwr_proto_BoolList;

typedef struct _flwr_proto_StringList {
    pb_callback_t vals;
} flwr_proto_StringList;

typedef struct _flwr_proto_BytesList {
    pb_callback_t vals;
} flwr_proto_BytesList;

typedef struct _flwr_proto_Array {
    pb_callback_t dtype;
    pb_callback_t shape;
    pb_callback_t stype;
    pb_callback_t data;
} flwr_proto_Array;

typedef struct _flwr_proto_MetricRecordValue {
    pb_size_t which_value;
    union _flwr_proto_MetricRecordValue_value {
        /* Single element */
        double double_;
        int64_t sint64;
        uint64_t uint64;
        /* List types */
        flwr_proto_DoubleList double_list;
        flwr_proto_SintList sint_list;
        flwr_proto_UintList uint_list;
    } value;
} flwr_proto_MetricRecordValue;

typedef struct _flwr_proto_ConfigRecordValue {
    pb_size_t which_value;
    union _flwr_proto_ConfigRecordValue_value {
        /* Single element */
        double double_;
        int64_t sint64;
        uint64_t uint64;
        bool bool_;
        pb_callback_t string;
        pb_callback_t bytes;
        /* List types */
        flwr_proto_DoubleList double_list;
        flwr_proto_SintList sint_list;
        flwr_proto_UintList uint_list;
        flwr_proto_BoolList bool_list;
        flwr_proto_StringList string_list;
        flwr_proto_BytesList bytes_list;
    } value;
} flwr_proto_ConfigRecordValue;

typedef struct _flwr_proto_ArrayRecord {
    pb_callback_t items;
} flwr_proto_ArrayRecord;

typedef struct _flwr_proto_ArrayRecord_Item {
    pb_callback_t key;
    bool has_value;
    flwr_proto_Array value;
} flwr_proto_ArrayRecord_Item;

typedef struct _flwr_proto_MetricRecord {
    pb_callback_t items;
} flwr_proto_MetricRecord;

typedef struct _flwr_proto_MetricRecord_Item {
    pb_callback_t key;
    bool has_value;
    flwr_proto_MetricRecordValue value;
} flwr_proto_MetricRecord_Item;

typedef struct _flwr_proto_ConfigRecord {
    pb_callback_t items;
} flwr_proto_ConfigRecord;

typedef struct _flwr_proto_ConfigRecord_Item {
    pb_callback_t key;
    bool has_value;
    flwr_proto_ConfigRecordValue value;
} flwr_proto_ConfigRecord_Item;

typedef struct _flwr_proto_RecordDict {
    pb_callback_t items;
} flwr_proto_RecordDict;

typedef struct _flwr_proto_RecordDict_Item {
    pb_callback_t key;
    pb_size_t which_value;
    union _flwr_proto_RecordDict_Item_value {
        flwr_proto_ArrayRecord array_record;
        flwr_proto_MetricRecord metric_record;
        flwr_proto_ConfigRecord config_record;
    } value;
} flwr_proto_RecordDict_Item;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define flwr_proto_DoubleList_init_default       {{{NULL}, NULL}}
#define flwr_proto_SintList_init_default         {{{NULL}, NULL}}
#define flwr_proto_UintList_init_default         {{{NULL}, NULL}}
#define flwr_proto_BoolList_init_default         {{{NULL}, NULL}}
#define flwr_proto_StringList_init_default       {{{NULL}, NULL}}
#define flwr_proto_BytesList_init_default        {{{NULL}, NULL}}
#define flwr_proto_Array_init_default            {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define flwr_proto_MetricRecordValue_init_default {0, {0}}
#define flwr_proto_ConfigRecordValue_init_default {0, {0}}
#define flwr_proto_ArrayRecord_init_default      {{{NULL}, NULL}}
#define flwr_proto_ArrayRecord_Item_init_default {{{NULL}, NULL}, false, flwr_proto_Array_init_default}
#define flwr_proto_MetricRecord_init_default     {{{NULL}, NULL}}
#define flwr_proto_MetricRecord_Item_init_default {{{NULL}, NULL}, false, flwr_proto_MetricRecordValue_init_default}
#define flwr_proto_ConfigRecord_init_default     {{{NULL}, NULL}}
#define flwr_proto_ConfigRecord_Item_init_default {{{NULL}, NULL}, false, flwr_proto_ConfigRecordValue_init_default}
#define flwr_proto_RecordDict_init_default       {{{NULL}, NULL}}
#define flwr_proto_RecordDict_Item_init_default  {{{NULL}, NULL}, 0, {flwr_proto_ArrayRecord_init_default}}
#define flwr_proto_DoubleList_init_zero          {{{NULL}, NULL}}
#define flwr_proto_SintList_init_zero            {{{NULL}, NULL}}
#define flwr_proto_UintList_init_zero            {{{NULL}, NULL}}
#define flwr_proto_BoolList_init_zero            {{{NULL}, NULL}}
#define flwr_proto_StringList_init_zero          {{{NULL}, NULL}}
#define flwr_proto_BytesList_init_zero           {{{NULL}, NULL}}
#define flwr_proto_Array_init_zero               {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define flwr_proto_MetricRecordValue_init_zero   {0, {0}}
#define flwr_proto_ConfigRecordValue_init_zero   {0, {0}}
#define flwr_proto_ArrayRecord_init_zero         {{{NULL}, NULL}}
#define flwr_proto_ArrayRecord_Item_init_zero    {{{NULL}, NULL}, false, flwr_proto_Array_init_zero}
#define flwr_proto_MetricRecord_init_zero        {{{NULL}, NULL}}
#define flwr_proto_MetricRecord_Item_init_zero   {{{NULL}, NULL}, false, flwr_proto_MetricRecordValue_init_zero}
#define flwr_proto_ConfigRecord_init_zero        {{{NULL}, NULL}}
#define flwr_proto_ConfigRecord_Item_init_zero   {{{NULL}, NULL}, false, flwr_proto_ConfigRecordValue_init_zero}
#define flwr_proto_RecordDict_init_zero          {{{NULL}, NULL}}
#define flwr_proto_RecordDict_Item_init_zero     {{{NULL}, NULL}, 0, {flwr_proto_ArrayRecord_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define flwr_proto_DoubleList_vals_tag           1
#define flwr_proto_SintList_vals_tag             1
#define flwr_proto_UintList_vals_tag             1
#define flwr_proto_BoolList_vals_tag             1
#define flwr_proto_StringList_vals_tag           1
#define flwr_proto_BytesList_vals_tag            1
#define flwr_proto_Array_dtype_tag               1
#define flwr_proto_Array_shape_tag               2
#define flwr_proto_Array_stype_tag               3
#define flwr_proto_Array_data_tag                4
#define flwr_proto_MetricRecordValue_double_tag  1
#define flwr_proto_MetricRecordValue_sint64_tag  2
#define flwr_proto_MetricRecordValue_uint64_tag  3
#define flwr_proto_MetricRecordValue_double_list_tag 21
#define flwr_proto_MetricRecordValue_sint_list_tag 22
#define flwr_proto_MetricRecordValue_uint_list_tag 23
#define flwr_proto_ConfigRecordValue_double_tag  1
#define flwr_proto_ConfigRecordValue_sint64_tag  2
#define flwr_proto_ConfigRecordValue_uint64_tag  3
#define flwr_proto_ConfigRecordValue_bool_tag    4
#define flwr_proto_ConfigRecordValue_string_tag  5
#define flwr_proto_ConfigRecordValue_bytes_tag   6
#define flwr_proto_ConfigRecordValue_double_list_tag 21
#define flwr_proto_ConfigRecordValue_sint_list_tag 22
#define flwr_proto_ConfigRecordValue_uint_list_tag 23
#define flwr_proto_ConfigRecordValue_bool_list_tag 24
#define flwr_proto_ConfigRecordValue_string_list_tag 25
#define flwr_proto_ConfigRecordValue_bytes_list_tag 26
#define flwr_proto_ArrayRecord_items_tag         1
#define flwr_proto_ArrayRecord_Item_key_tag      1
#define flwr_proto_ArrayRecord_Item_value_tag    2
#define flwr_proto_MetricRecord_items_tag        1
#define flwr_proto_MetricRecord_Item_key_tag     1
#define flwr_proto_MetricRecord_Item_value_tag   2
#define flwr_proto_ConfigRecord_items_tag        1
#define flwr_proto_ConfigRecord_Item_key_tag     1
#define flwr_proto_ConfigRecord_Item_value_tag   2
#define flwr_proto_RecordDict_items_tag          1
#define flwr_proto_RecordDict_Item_key_tag       1
#define flwr_proto_RecordDict_Item_array_record_tag 2
#define flwr_proto_RecordDict_Item_metric_record_tag 3
#define flwr_proto_RecordDict_Item_config_record_tag 4

/* Struct field encoding specification for nanopb */
#define flwr_proto_DoubleList_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, DOUBLE,   vals,              1)
#define flwr_proto_DoubleList_CALLBACK pb_default_field_callback
#define flwr_proto_DoubleList_DEFAULT NULL

#define flwr_proto_SintList_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, SINT64,   vals,              1)
#define flwr_proto_SintList_CALLBACK pb_default_field_callback
#define flwr_proto_SintList_DEFAULT NULL

#define flwr_proto_UintList_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, UINT64,   vals,              1)
#define flwr_proto_UintList_CALLBACK pb_default_field_callback
#define flwr_proto_UintList_DEFAULT NULL

#define flwr_proto_BoolList_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, BOOL,     vals,              1)
#define flwr_proto_BoolList_CALLBACK pb_default_field_callback
#define flwr_proto_BoolList_DEFAULT NULL

#define flwr_proto_StringList_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, STRING,   vals,              1)
#define flwr_proto_StringList_CALLBACK pb_default_field_callback
#define flwr_proto_StringList_DEFAULT NULL

#define flwr_proto_BytesList_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, BYTES,    vals,              1)
#define flwr_proto_BytesList_CALLBACK pb_default_field_callback
#define flwr_proto_BytesList_DEFAULT NULL

#define flwr_proto_Array_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   dtype,             1) \
X(a, CALLBACK, REPEATED, INT32,    shape,             2) \
X(a, CALLBACK, SINGULAR, STRING,   stype,             3) \
X(a, CALLBACK, SINGULAR, BYTES,    data,              4)
#define flwr_proto_Array_CALLBACK pb_default_field_callback
#define flwr_proto_Array_DEFAULT NULL

#define flwr_proto_MetricRecordValue_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    DOUBLE,   (value,double_,value.double_),   1) \
X(a, STATIC,   ONEOF,    SINT64,   (value,sint64,value.sint64),   2) \
X(a, STATIC,   ONEOF,    UINT64,   (value,uint64,value.uint64),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (value,double_list,value.double_list),  21) \
X(a, STATIC,   ONEOF,    MESSAGE,  (value,sint_list,value.sint_list),  22) \
X(a, STATIC,   ONEOF,    MESSAGE,  (value,uint_list,value.uint_list),  23)
#define flwr_proto_MetricRecordValue_CALLBACK NULL
#define flwr_proto_MetricRecordValue_DEFAULT NULL
#define flwr_proto_MetricRecordValue_value_double_list_MSGTYPE flwr_proto_DoubleList
#define flwr_proto_MetricRecordValue_value_sint_list_MSGTYPE flwr_proto_SintList
#define flwr_proto_MetricRecordValue_value_uint_list_MSGTYPE flwr_proto_UintList

#define flwr_proto_ConfigRecordValue_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    DOUBLE,   (value,double_,value.double_),   1) \
X(a, STATIC,   ONEOF,    SINT64,   (value,sint64,value.sint64),   2) \
X(a, STATIC,   ONEOF,    UINT64,   (value,uint64,value.uint64),   3) \
X(a, STATIC,   ONEOF,    BOOL,     (value,bool_,value.bool_),   4) \
X(a, CALLBACK, ONEOF,    STRING,   (value,string,value.string),   5) \
X(a, CALLBACK, ONEOF,    BYTES,    (value,bytes,value.bytes),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (value,double_list,value.double_list),  21) \
X(a, STATIC,   ONEOF,    MESSAGE,  (value,sint_list,value.sint_list),  22) \
X(a, STATIC,   ONEOF,    MESSAGE,  (value,uint_list,value.uint_list),  23) \
X(a, STATIC,   ONEOF,    MESSAGE,  (value,bool_list,value.bool_list),  24) \
X(a, STATIC,   ONEOF,    MESSAGE,  (value,string_list,value.string_list),  25) \
X(a, STATIC,   ONEOF,    MESSAGE,  (value,bytes_list,value.bytes_list),  26)
#define flwr_proto_ConfigRecordValue_CALLBACK pb_default_field_callback
#define flwr_proto_ConfigRecordValue_DEFAULT NULL
#define flwr_proto_ConfigRecordValue_value_double_list_MSGTYPE flwr_proto_DoubleList
#define flwr_proto_ConfigRecordValue_value_sint_list_MSGTYPE flwr_proto_SintList
#define flwr_proto_ConfigRecordValue_value_uint_list_MSGTYPE flwr_proto_UintList
#define flwr_proto_ConfigRecordValue_value_bool_list_MSGTYPE flwr_proto_BoolList
#define flwr_proto_ConfigRecordValue_value_string_list_MSGTYPE flwr_proto_StringList
#define flwr_proto_ConfigRecordValue_value_bytes_list_MSGTYPE flwr_proto_BytesList

#define flwr_proto_ArrayRecord_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  items,             1)
#define flwr_proto_ArrayRecord_CALLBACK pb_default_field_callback
#define flwr_proto_ArrayRecord_DEFAULT NULL
#define flwr_proto_ArrayRecord_items_MSGTYPE flwr_proto_ArrayRecord_Item

#define flwr_proto_ArrayRecord_Item_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define flwr_proto_ArrayRecord_Item_CALLBACK pb_default_field_callback
#define flwr_proto_ArrayRecord_Item_DEFAULT NULL
#define flwr_proto_ArrayRecord_Item_value_MSGTYPE flwr_proto_Array

#define flwr_proto_MetricRecord_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  items,             1)
#define flwr_proto_MetricRecord_CALLBACK pb_default_field_callback
#define flwr_proto_MetricRecord_DEFAULT NULL
#define flwr_proto_MetricRecord_items_MSGTYPE flwr_proto_MetricRecord_Item

#define flwr_proto_MetricRecord_Item_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define flwr_proto_MetricRecord_Item_CALLBACK pb_default_field_callback
#define flwr_proto_MetricRecord_Item_DEFAULT NULL
#define flwr_proto_MetricRecord_Item_value_MSGTYPE flwr_proto_MetricRecordValue

#define flwr_proto_ConfigRecord_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  items,             1)
#define flwr_proto_ConfigRecord_CALLBACK pb_default_field_callback
#define flwr_proto_ConfigRecord_DEFAULT NULL
#define flwr_proto_ConfigRecord_items_MSGTYPE flwr_proto_ConfigRecord_Item

#define flwr_proto_ConfigRecord_Item_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define flwr_proto_ConfigRecord_Item_CALLBACK pb_default_field_callback
#define flwr_proto_ConfigRecord_Item_DEFAULT NULL
#define flwr_proto_ConfigRecord_Item_value_MSGTYPE flwr_proto_ConfigRecordValue

#define flwr_proto_RecordDict_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  items,             1)
#define flwr_proto_RecordDict_CALLBACK pb_default_field_callback
#define flwr_proto_RecordDict_DEFAULT NULL
#define flwr_proto_RecordDict_items_MSGTYPE flwr_proto_RecordDict_Item

#define flwr_proto_RecordDict_Item_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (value,array_record,value.array_record),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (value,metric_record,value.metric_record),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (value,config_record,value.config_record),   4)
#define flwr_proto_RecordDict_Item_CALLBACK pb_default_field_callback
#define flwr_proto_RecordDict_Item_DEFAULT NULL
#define flwr_proto_RecordDict_Item_value_array_record_MSGTYPE flwr_proto_ArrayRecord
#define flwr_proto_RecordDict_Item_value_metric_record_MSGTYPE flwr_proto_MetricRecord
#define flwr_proto_RecordDict_Item_value_config_record_MSGTYPE flwr_proto_ConfigRecord

extern const pb_msgdesc_t flwr_proto_DoubleList_msg;
extern const pb_msgdesc_t flwr_proto_SintList_msg;
extern const pb_msgdesc_t flwr_proto_UintList_msg;
extern const pb_msgdesc_t flwr_proto_BoolList_msg;
extern const pb_msgdesc_t flwr_proto_StringList_msg;
extern const pb_msgdesc_t flwr_proto_BytesList_msg;
extern const pb_msgdesc_t flwr_proto_Array_msg;
extern const pb_msgdesc_t flwr_proto_MetricRecordValue_msg;
extern const pb_msgdesc_t flwr_proto_ConfigRecordValue_msg;
extern const pb_msgdesc_t flwr_proto_ArrayRecord_msg;
extern const pb_msgdesc_t flwr_proto_ArrayRecord_Item_msg;
extern const pb_msgdesc_t flwr_proto_MetricRecord_msg;
extern const pb_msgdesc_t flwr_proto_MetricRecord_Item_msg;
extern const pb_msgdesc_t flwr_proto_ConfigRecord_msg;
extern const pb_msgdesc_t flwr_proto_ConfigRecord_Item_msg;
extern const pb_msgdesc_t flwr_proto_RecordDict_msg;
extern const pb_msgdesc_t flwr_proto_RecordDict_Item_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define flwr_proto_DoubleList_fields &flwr_proto_DoubleList_msg
#define flwr_proto_SintList_fields &flwr_proto_SintList_msg
#define flwr_proto_UintList_fields &flwr_proto_UintList_msg
#define flwr_proto_BoolList_fields &flwr_proto_BoolList_msg
#define flwr_proto_StringList_fields &flwr_proto_StringList_msg
#define flwr_proto_BytesList_fields &flwr_proto_BytesList_msg
#define flwr_proto_Array_fields &flwr_proto_Array_msg
#define flwr_proto_MetricRecordValue_fields &flwr_proto_MetricRecordValue_msg
#define flwr_proto_ConfigRecordValue_fields &flwr_proto_ConfigRecordValue_msg
#define flwr_proto_ArrayRecord_fields &flwr_proto_ArrayRecord_msg
#define flwr_proto_ArrayRecord_Item_fields &flwr_proto_ArrayRecord_Item_msg
#define flwr_proto_MetricRecord_fields &flwr_proto_MetricRecord_msg
#define flwr_proto_MetricRecord_Item_fields &flwr_proto_MetricRecord_Item_msg
#define flwr_proto_ConfigRecord_fields &flwr_proto_ConfigRecord_msg
#define flwr_proto_ConfigRecord_Item_fields &flwr_proto_ConfigRecord_Item_msg
#define flwr_proto_RecordDict_fields &flwr_proto_RecordDict_msg
#define flwr_proto_RecordDict_Item_fields &flwr_proto_RecordDict_Item_msg

/* Maximum encoded size of messages (where known) */
/* flwr_proto_DoubleList_size depends on runtime parameters */
/* flwr_proto_SintList_size depends on runtime parameters */
/* flwr_proto_UintList_size depends on runtime parameters */
/* flwr_proto_BoolList_size depends on runtime parameters */
/* flwr_proto_StringList_size depends on runtime parameters */
/* flwr_proto_BytesList_size depends on runtime parameters */
/* flwr_proto_Array_size depends on runtime parameters */
/* flwr_proto_MetricRecordValue_size depends on runtime parameters */
/* flwr_proto_ConfigRecordValue_size depends on runtime parameters */
/* flwr_proto_ArrayRecord_size depends on runtime parameters */
/* flwr_proto_ArrayRecord_Item_size depends on runtime parameters */
/* flwr_proto_MetricRecord_size depends on runtime parameters */
/* flwr_proto_MetricRecord_Item_size depends on runtime parameters */
/* flwr_proto_ConfigRecord_size depends on runtime parameters */
/* flwr_proto_ConfigRecord_Item_size depends on runtime parameters */
/* flwr_proto_RecordDict_size depends on runtime parameters */
/* flwr_proto_RecordDict_Item_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
