/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "proto/recorddict.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(flwr_proto_DoubleList, flwr_proto_DoubleList, AUTO)


PB_BIND(flwr_proto_SintList, flwr_proto_SintList, AUTO)


PB_BIND(flwr_proto_UintList, flwr_proto_UintList, AUTO)


PB_BIND(flwr_proto_BoolList, flwr_proto_BoolList, AUTO)


PB_BIND(flwr_proto_StringList, flwr_proto_StringList, AUTO)


PB_BIND(flwr_proto_BytesList, flwr_proto_BytesList, AUTO)


PB_BIND(flwr_proto_Array, flwr_proto_Array, AUTO)


PB_BIND(flwr_proto_MetricRecordValue, flwr_proto_MetricRecordValue, AUTO)


PB_BIND(flwr_proto_ConfigRecordValue, flwr_proto_ConfigRecordValue, AUTO)


PB_BIND(flwr_proto_ArrayRecord, flwr_proto_ArrayRecord, AUTO)


PB_BIND(flwr_proto_ArrayRecord_Item, flwr_proto_ArrayRecord_Item, AUTO)


PB_BIND(flwr_proto_MetricRecord, flwr_proto_MetricRecord, AUTO)


PB_BIND(flwr_proto_MetricRecord_Item, flwr_proto_MetricRecord_Item, AUTO)


PB_BIND(flwr_proto_ConfigRecord, flwr_proto_ConfigRecord, AUTO)


PB_BIND(flwr_proto_ConfigRecord_Item, flwr_proto_ConfigRecord_Item, AUTO)


PB_BIND(flwr_proto_RecordDict, flwr_proto_RecordDict, AUTO)


PB_BIND(flwr_proto_RecordDict_Item, flwr_proto_RecordDict_Item, AUTO)



#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

