/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_FLWR_PROTO_PROTO_TASK_PB_H_INCLUDED
#define PB_FLWR_PROTO_PROTO_TASK_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _flwr_proto_TaskStatus {
    /* "pending", "starting", "running", or "finished" */
    pb_callback_t status;
    /* "completed", "failed", "stopped" or "" (non-finished) */
    pb_callback_t sub_status;
    /* failure details */
    pb_callback_t details;
} flwr_proto_TaskStatus;

typedef struct _flwr_proto_Task {
    uint64_t task_id;
    pb_callback_t type;
    uint64_t run_id;
    bool has_status;
    flwr_proto_TaskStatus status;
    pb_callback_t pending_at;
    pb_callback_t starting_at;
    pb_callback_t running_at;
    pb_callback_t finished_at;
    pb_callback_t fab_hash;
    pb_callback_t model_ref;
    pb_callback_t connector_ref;
} flwr_proto_Task;

typedef struct _flwr_proto_TaskEvent {
    uint64_t id;
    pb_callback_t timestamp;
    uint64_t run_id;
    uint64_t task_id;
    pb_callback_t event;
    pb_callback_t data;
} flwr_proto_TaskEvent;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define flwr_proto_Task_init_default             {0, {{NULL}, NULL}, 0, false, flwr_proto_TaskStatus_init_default, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define flwr_proto_TaskStatus_init_default       {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define flwr_proto_TaskEvent_init_default        {0, {{NULL}, NULL}, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define flwr_proto_Task_init_zero                {0, {{NULL}, NULL}, 0, false, flwr_proto_TaskStatus_init_zero, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define flwr_proto_TaskStatus_init_zero          {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define flwr_proto_TaskEvent_init_zero           {0, {{NULL}, NULL}, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define flwr_proto_TaskStatus_status_tag         1
#define flwr_proto_TaskStatus_sub_status_tag     2
#define flwr_proto_TaskStatus_details_tag        3
#define flwr_proto_Task_task_id_tag              1
#define flwr_proto_Task_type_tag                 2
#define flwr_proto_Task_run_id_tag               3
#define flwr_proto_Task_status_tag               4
#define flwr_proto_Task_pending_at_tag           5
#define flwr_proto_Task_starting_at_tag          6
#define flwr_proto_Task_running_at_tag           7
#define flwr_proto_Task_finished_at_tag          8
#define flwr_proto_Task_fab_hash_tag             9
#define flwr_proto_Task_model_ref_tag            10
#define flwr_proto_Task_connector_ref_tag        11
#define flwr_proto_TaskEvent_id_tag              1
#define flwr_proto_TaskEvent_timestamp_tag       2
#define flwr_proto_TaskEvent_run_id_tag          3
#define flwr_proto_TaskEvent_task_id_tag         4
#define flwr_proto_TaskEvent_event_tag           5
#define flwr_proto_TaskEvent_data_tag            6

/* Struct field encoding specification for nanopb */
#define flwr_proto_Task_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   task_id,           1) \
X(a, CALLBACK, SINGULAR, STRING,   type,              2) \
X(a, STATIC,   SINGULAR, UINT64,   run_id,            3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  status,            4) \
X(a, CALLBACK, SINGULAR, STRING,   pending_at,        5) \
X(a, CALLBACK, SINGULAR, STRING,   starting_at,       6) \
X(a, CALLBACK, SINGULAR, STRING,   running_at,        7) \
X(a, CALLBACK, SINGULAR, STRING,   finished_at,       8) \
X(a, CALLBACK, OPTIONAL, STRING,   fab_hash,          9) \
X(a, CALLBACK, OPTIONAL, STRING,   model_ref,        10) \
X(a, CALLBACK, OPTIONAL, STRING,   connector_ref,    11)
#define flwr_proto_Task_CALLBACK pb_default_field_callback
#define flwr_proto_Task_DEFAULT NULL
#define flwr_proto_Task_status_MSGTYPE flwr_proto_TaskStatus

#define flwr_proto_TaskStatus_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   status,            1) \
X(a, CALLBACK, SINGULAR, STRING,   sub_status,        2) \
X(a, CALLBACK, SINGULAR, STRING,   details,           3)
#define flwr_proto_TaskStatus_CALLBACK pb_default_field_callback
#define flwr_proto_TaskStatus_DEFAULT NULL

#define flwr_proto_TaskEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   id,                1) \
X(a, CALLBACK, SINGULAR, STRING,   timestamp,         2) \
X(a, STATIC,   SINGULAR, UINT64,   run_id,            3) \
X(a, STATIC,   SINGULAR, UINT64,   task_id,           4) \
X(a, CALLBACK, SINGULAR, STRING,   event,             5) \
X(a, CALLBACK, SINGULAR, STRING,   data,              6)
#define flwr_proto_TaskEvent_CALLBACK pb_default_field_callback
#define flwr_proto_TaskEvent_DEFAULT NULL

extern const pb_msgdesc_t flwr_proto_Task_msg;
extern const pb_msgdesc_t flwr_proto_TaskStatus_msg;
extern const pb_msgdesc_t flwr_proto_TaskEvent_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define flwr_proto_Task_fields &flwr_proto_Task_msg
#define flwr_proto_TaskStatus_fields &flwr_proto_TaskStatus_msg
#define flwr_proto_TaskEvent_fields &flwr_proto_TaskEvent_msg

/* Maximum encoded size of messages (where known) */
/* flwr_proto_Task_size depends on runtime parameters */
/* flwr_proto_TaskStatus_size depends on runtime parameters */
/* flwr_proto_TaskEvent_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
