/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "proto/task.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(flwr_proto_Task, flwr_proto_Task, AUTO)


PB_BIND(flwr_proto_TaskStatus, flwr_proto_TaskStatus, AUTO)


PB_BIND(flwr_proto_TaskEvent, flwr_proto_TaskEvent, AUTO)



