/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_FLWR_PROTO_PROTO_TRANSPORT_PB_H_INCLUDED
#define PB_FLWR_PROTO_PROTO_TRANSPORT_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _Code {
    Code_OK = 0,
    Code_GET_PROPERTIES_NOT_IMPLEMENTED = 1,
    Code_GET_PARAMETERS_NOT_IMPLEMENTED = 2,
    Code_FIT_NOT_IMPLEMENTED = 3,
    Code_EVALUATE_NOT_IMPLEMENTED = 4
} Code;

typedef enum _Reason {
    Reason_UNKNOWN = 0,
    Reason_RECONNECT = 1,
    Reason_POWER_DISCONNECTED = 2,
    Reason_WIFI_UNAVAILABLE = 3,
    Reason_ACK = 4
} Reason;

/* Struct definitions */
typedef struct _Status {
    Code code;
    pb_callback_t message;
} Status;

typedef struct _Parameters {
    pb_callback_t tensors;
    pb_callback_t tensor_type;
} Parameters;

typedef struct _ServerMessage_ReconnectIns {
    int64_t seconds;
} ServerMessage_ReconnectIns;

typedef struct _ServerMessage_GetPropertiesIns {
    pb_callback_t config;
} ServerMessage_GetPropertiesIns;

typedef struct _ServerMessage_GetParametersIns {
    pb_callback_t config;
} ServerMessage_GetParametersIns;

typedef struct _ServerMessage_FitIns {
    bool has_parameters;
    Parameters parameters;
    pb_callback_t config;
} ServerMessage_FitIns;

typedef struct _ServerMessage_EvaluateIns {
    bool has_parameters;
    Parameters parameters;
    pb_callback_t config;
} ServerMessage_EvaluateIns;

typedef struct _ServerMessage {
    pb_size_t which_msg;
    union _ServerMessage_msg {
        ServerMessage_ReconnectIns reconnect_ins;
        ServerMessage_GetPropertiesIns get_properties_ins;
        ServerMessage_GetParametersIns get_parameters_ins;
        ServerMessage_FitIns fit_ins;
        ServerMessage_EvaluateIns evaluate_ins;
    } msg;
} ServerMessage;

typedef struct _ClientMessage_DisconnectRes {
    Reason reason;
} ClientMessage_DisconnectRes;

typedef struct _ClientMessage_GetPropertiesRes {
    bool has_status;
    Status status;
    pb_callback_t properties;
} ClientMessage_GetPropertiesRes;

typedef struct _ClientMessage_GetParametersRes {
    bool has_status;
    Status status;
    bool has_parameters;
    Parameters parameters;
} ClientMessage_GetParametersRes;

typedef struct _ClientMessage_FitRes {
    bool has_status;
    Status status;
    bool has_parameters;
    Parameters parameters;
    int64_t num_examples;
    pb_callback_t metrics;
} ClientMessage_FitRes;

typedef struct _ClientMessage_EvaluateRes {
    bool has_status;
    Status status;
    float loss;
    int64_t num_examples;
    pb_callback_t metrics;
} ClientMessage_EvaluateRes;

typedef struct _ClientMessage {
    pb_size_t which_msg;
    union _ClientMessage_msg {
        ClientMessage_DisconnectRes disconnect_res;
        ClientMessage_GetPropertiesRes get_properties_res;
        ClientMessage_GetParametersRes get_parameters_res;
        ClientMessage_FitRes fit_res;
        ClientMessage_EvaluateRes evaluate_res;
    } msg;
} ClientMessage;

typedef struct _Scalar {
    pb_size_t which_scalar;
    union _Scalar_scalar {
        double double_;
        /* float float = 2;
     int32 int32 = 3;
     int64 int64 = 4;
     uint32 uint32 = 5; */
        uint64_t uint64;
        /* sint32 sint32 = 7; */
        int64_t sint64;
        /* fixed32 fixed32 = 9;
     fixed64 fixed64 = 10;
     sfixed32 sfixed32 = 11;
     sfixed64 sfixed64 = 12; */
        bool bool_;
        pb_callback_t string;
        pb_callback_t bytes;
    } scalar;
} Scalar;

typedef struct _ServerMessage_GetPropertiesIns_ConfigEntry {
    pb_callback_t key;
    bool has_value;
    Scalar value;
} ServerMessage_GetPropertiesIns_ConfigEntry;

typedef struct _ServerMessage_GetParametersIns_ConfigEntry {
    pb_callback_t key;
    bool has_value;
    Scalar value;
} ServerMessage_GetParametersIns_ConfigEntry;

typedef struct _ServerMessage_FitIns_ConfigEntry {
    pb_callback_t key;
    bool has_value;
    Scalar value;
} ServerMessage_FitIns_ConfigEntry;

typedef struct _ServerMessage_EvaluateIns_ConfigEntry {
    pb_callback_t key;
    bool has_value;
    Scalar value;
} ServerMessage_EvaluateIns_ConfigEntry;

typedef struct _ClientMessage_GetPropertiesRes_PropertiesEntry {
    pb_callback_t key;
    bool has_value;
    Scalar value;
} ClientMessage_GetPropertiesRes_PropertiesEntry;

typedef struct _ClientMessage_FitRes_MetricsEntry {
    pb_callback_t key;
    bool has_value;
    Scalar value;
} ClientMessage_FitRes_MetricsEntry;

typedef struct _ClientMessage_EvaluateRes_MetricsEntry {
    pb_callback_t key;
    bool has_value;
    Scalar value;
} ClientMessage_EvaluateRes_MetricsEntry;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _Code_MIN Code_OK
#define _Code_MAX Code_EVALUATE_NOT_IMPLEMENTED
#define _Code_ARRAYSIZE ((Code)(Code_EVALUATE_NOT_IMPLEMENTED+1))

#define _Reason_MIN Reason_UNKNOWN
#define _Reason_MAX Reason_ACK
#define _Reason_ARRAYSIZE ((Reason)(Reason_ACK+1))

#define Status_code_ENUMTYPE Code













#define ClientMessage_DisconnectRes_reason_ENUMTYPE Reason










/* Initializer values for message structs */
#define Status_init_default           {_Code_MIN, {{NULL}, NULL}}
#define Parameters_init_default       {{{NULL}, NULL}, {{NULL}, NULL}}
#define ServerMessage_init_default    {0, {ServerMessage_ReconnectIns_init_default}}
#define ServerMessage_ReconnectIns_init_default {0}
#define ServerMessage_GetPropertiesIns_init_default {{{NULL}, NULL}}
#define ServerMessage_GetPropertiesIns_ConfigEntry_init_default {{{NULL}, NULL}, false, Scalar_init_default}
#define ServerMessage_GetParametersIns_init_default {{{NULL}, NULL}}
#define ServerMessage_GetParametersIns_ConfigEntry_init_default {{{NULL}, NULL}, false, Scalar_init_default}
#define ServerMessage_FitIns_init_default {false, Parameters_init_default, {{NULL}, NULL}}
#define ServerMessage_FitIns_ConfigEntry_init_default {{{NULL}, NULL}, false, Scalar_init_default}
#define ServerMessage_EvaluateIns_init_default {false, Parameters_init_default, {{NULL}, NULL}}
#define ServerMessage_EvaluateIns_ConfigEntry_init_default {{{NULL}, NULL}, false, Scalar_init_default}
#define ClientMessage_init_default    {0, {ClientMessage_DisconnectRes_init_default}}
#define ClientMessage_DisconnectRes_init_default {_Reason_MIN}
#define ClientMessage_GetPropertiesRes_init_default {false, Status_init_default, {{NULL}, NULL}}
#define ClientMessage_GetPropertiesRes_PropertiesEntry_init_default {{{NULL}, NULL}, false, Scalar_init_default}
#define ClientMessage_GetParametersRes_init_default {false, Status_init_default, false, Parameters_init_default}
#define ClientMessage_FitRes_init_default {false, Status_init_default, false, Parameters_init_default, 0, {{NULL}, NULL}}
#define ClientMessage_FitRes_MetricsEntry_init_default {{{NULL}, NULL}, false, Scalar_init_default}
#define ClientMessage_EvaluateRes_init_default {false, Status_init_default, 0, 0, {{NULL}, NULL}}
#define ClientMessage_EvaluateRes_MetricsEntry_init_default {{{NULL}, NULL}, false, Scalar_init_default}
#define Scalar_init_default           {0, {0}}
#define Status_init_zero              {_Code_MIN, {{NULL}, NULL}}
#define Parameters_init_zero          {{{NULL}, NULL}, {{NULL}, NULL}}
#define ServerMessage_init_zero       {0, {ServerMessage_ReconnectIns_init_zero}}
#define ServerMessage_ReconnectIns_init_zero {0}
#define ServerMessage_GetPropertiesIns_init_zero {{{NULL}, NULL}}
#define ServerMessage_GetPropertiesIns_ConfigEntry_init_zero {{{NULL}, NULL}, false, Scalar_init_zero}
#define ServerMessage_GetParametersIns_init_zero {{{NULL}, NULL}}
#define ServerMessage_GetParametersIns_ConfigEntry_init_zero {{{NULL}, NULL}, false, Scalar_init_zero}
#define ServerMessage_FitIns_init_zero {false, Parameters_init_zero, {{NULL}, NULL}}
#define ServerMessage_FitIns_ConfigEntry_init_zero {{{NULL}, NULL}, false, Scalar_init_zero}
#define ServerMessage_EvaluateIns_init_zero {false, Parameters_init_zero, {{NULL}, NULL}}
#define ServerMessage_EvaluateIns_ConfigEntry_init_zero {{{NULL}, NULL}, false, Scalar_init_zero}
#define ClientMessage_init_zero       {0, {ClientMessage_DisconnectRes_init_zero}}
#define ClientMessage_DisconnectRes_init_zero {_Reason_MIN}
#define ClientMessage_GetPropertiesRes_init_zero {false, Status_init_zero, {{NULL}, NULL}}
#define ClientMessage_GetPropertiesRes_PropertiesEntry_init_zero {{{NULL}, NULL}, false, Scalar_init_zero}
#define ClientMessage_GetParametersRes_init_zero {false, Status_init_zero, false, Parameters_init_zero}
#define ClientMessage_FitRes_init_zero {false, Status_init_zero, false, Parameters_init_zero, 0, {{NULL}, NULL}}
#define ClientMessage_FitRes_MetricsEntry_init_zero {{{NULL}, NULL}, false, Scalar_init_zero}
#define ClientMessage_EvaluateRes_init_zero {false, Status_init_zero, 0, 0, {{NULL}, NULL}}
#define ClientMessage_EvaluateRes_MetricsEntry_init_zero {{{NULL}, NULL}, false, Scalar_init_zero}
#define Scalar_init_zero              {0, {0}}

/* Field tags (for use in manual encoding/decoding) */
#define Status_code_tag               1
#define Status_message_tag            2
#define Parameters_tensors_tag        1
#define Parameters_tensor_type_tag    2
#define ServerMessage_ReconnectIns_seconds_tag 1
#define ServerMessage_GetPropertiesIns_config_tag 1
#define ServerMessage_GetParametersIns_config_tag 1
#define ServerMessage_FitIns_parameters_tag 1
#define ServerMessage_FitIns_config_tag 2
#define ServerMessage_EvaluateIns_parameters_tag 1
#define ServerMessage_EvaluateIns_config_tag 2
#define ServerMessage_reconnect_ins_tag 1
#define ServerMessage_get_properties_ins_tag 2
#define ServerMessage_get_parameters_ins_tag 3
#define ServerMessage_fit_ins_tag     4
#define ServerMessage_evaluate_ins_tag 5
#define ClientMessage_DisconnectRes_reason_tag 1
#define ClientMessage_GetPropertiesRes_status_tag 1
#define ClientMessage_GetPropertiesRes_properties_tag 2
#define ClientMessage_GetParametersRes_status_tag 1
#define ClientMessage_GetParametersRes_parameters_tag 2
#define ClientMessage_FitRes_status_tag 1
#define ClientMessage_FitRes_parameters_tag 2
#define ClientMessage_FitRes_num_examples_tag 3
#define ClientMessage_FitRes_metrics_tag 4
#define ClientMessage_EvaluateRes_status_tag 1
#define ClientMessage_EvaluateRes_loss_tag 2
#define ClientMessage_EvaluateRes_num_examples_tag 3
#define ClientMessage_EvaluateRes_metrics_tag 4
#define ClientMessage_disconnect_res_tag 1
#define ClientMessage_get_properties_res_tag 2
#define ClientMessage_get_parameters_res_tag 3
#define ClientMessage_fit_res_tag     4
#define ClientMessage_evaluate_res_tag 5
#define Scalar_double_tag             1
#define Scalar_uint64_tag             6
#define Scalar_sint64_tag             8
#define Scalar_bool_tag               13
#define Scalar_string_tag             14
#define Scalar_bytes_tag              15
#define ServerMessage_GetPropertiesIns_ConfigEntry_key_tag 1
#define ServerMessage_GetPropertiesIns_ConfigEntry_value_tag 2
#define ServerMessage_GetParametersIns_ConfigEntry_key_tag 1
#define ServerMessage_GetParametersIns_ConfigEntry_value_tag 2
#define ServerMessage_FitIns_ConfigEntry_key_tag 1
#define ServerMessage_FitIns_ConfigEntry_value_tag 2
#define ServerMessage_EvaluateIns_ConfigEntry_key_tag 1
#define ServerMessage_EvaluateIns_ConfigEntry_value_tag 2
#define ClientMessage_GetPropertiesRes_PropertiesEntry_key_tag 1
#define ClientMessage_GetPropertiesRes_PropertiesEntry_value_tag 2
#define ClientMessage_FitRes_MetricsEntry_key_tag 1
#define ClientMessage_FitRes_MetricsEntry_value_tag 2
#define ClientMessage_EvaluateRes_MetricsEntry_key_tag 1
#define ClientMessage_EvaluateRes_MetricsEntry_value_tag 2

/* Struct field encoding specification for nanopb */
#define Status_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    code,              1) \
X(a, CALLBACK, SINGULAR, STRING,   message,           2)
#define Status_CALLBACK pb_default_field_callback
#define Status_DEFAULT NULL

#define Parameters_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, BYTES,    tensors,           1) \
X(a, CALLBACK, SINGULAR, STRING,   tensor_type,       2)
#define Parameters_CALLBACK pb_default_field_callback
#define Parameters_DEFAULT NULL

#define ServerMessage_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,reconnect_ins,msg.reconnect_ins),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,get_properties_ins,msg.get_properties_ins),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,get_parameters_ins,msg.get_parameters_ins),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,fit_ins,msg.fit_ins),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,evaluate_ins,msg.evaluate_ins),   5)
#define ServerMessage_CALLBACK NULL
#define ServerMessage_DEFAULT NULL
#define ServerMessage_msg_reconnect_ins_MSGTYPE ServerMessage_ReconnectIns
#define ServerMessage_msg_get_properties_ins_MSGTYPE ServerMessage_GetPropertiesIns
#define ServerMessage_msg_get_parameters_ins_MSGTYPE ServerMessage_GetParametersIns
#define ServerMessage_msg_fit_ins_MSGTYPE ServerMessage_FitIns
#define ServerMessage_msg_evaluate_ins_MSGTYPE ServerMessage_EvaluateIns

#define ServerMessage_ReconnectIns_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    seconds,           1)
#define ServerMessage_ReconnectIns_CALLBACK NULL
#define ServerMessage_ReconnectIns_DEFAULT NULL

#define ServerMessage_GetPropertiesIns_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  config,            1)
#define ServerMessage_GetPropertiesIns_CALLBACK pb_default_field_callback
#define ServerMessage_GetPropertiesIns_DEFAULT NULL
#define ServerMessage_GetPropertiesIns_config_MSGTYPE ServerMessage_GetPropertiesIns_ConfigEntry

#define ServerMessage_GetPropertiesIns_ConfigEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define ServerMessage_GetPropertiesIns_ConfigEntry_CALLBACK pb_default_field_callback
#define ServerMessage_GetPropertiesIns_ConfigEntry_DEFAULT NULL
#define ServerMessage_GetPropertiesIns_ConfigEntry_value_MSGTYPE Scalar

#define ServerMessage_GetParametersIns_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  config,            1)
#define ServerMessage_GetParametersIns_CALLBACK pb_default_field_callback
#define ServerMessage_GetParametersIns_DEFAULT NULL
#define ServerMessage_GetParametersIns_config_MSGTYPE ServerMessage_GetParametersIns_ConfigEntry

#define ServerMessage_GetParametersIns_ConfigEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define ServerMessage_GetParametersIns_ConfigEntry_CALLBACK pb_default_field_callback
#define ServerMessage_GetParametersIns_ConfigEntry_DEFAULT NULL
#define ServerMessage_GetParametersIns_ConfigEntry_value_MSGTYPE Scalar

#define ServerMessage_FitIns_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  parameters,        1) \
X(a, CALLBACK, REPEATED, MESSAGE,  config,            2)
#define ServerMessage_FitIns_CALLBACK pb_default_field_callback
#define ServerMessage_FitIns_DEFAULT NULL
#define ServerMessage_FitIns_parameters_MSGTYPE Parameters
#define ServerMessage_FitIns_config_MSGTYPE ServerMessage_FitIns_ConfigEntry

#define ServerMessage_FitIns_ConfigEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define ServerMessage_FitIns_ConfigEntry_CALLBACK pb_default_field_callback
#define ServerMessage_FitIns_ConfigEntry_DEFAULT NULL
#define ServerMessage_FitIns_ConfigEntry_value_MSGTYPE Scalar

#define ServerMessage_EvaluateIns_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  parameters,        1) \
X(a, CALLBACK, REPEATED, MESSAGE,  config,            2)
#define ServerMessage_EvaluateIns_CALLBACK pb_default_field_callback
#define ServerMessage_EvaluateIns_DEFAULT NULL
#define ServerMessage_EvaluateIns_parameters_MSGTYPE Parameters
#define ServerMessage_EvaluateIns_config_MSGTYPE ServerMessage_EvaluateIns_ConfigEntry

#define ServerMessage_EvaluateIns_ConfigEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define ServerMessage_EvaluateIns_ConfigEntry_CALLBACK pb_default_field_callback
#define ServerMessage_EvaluateIns_ConfigEntry_DEFAULT NULL
#define ServerMessage_EvaluateIns_ConfigEntry_value_MSGTYPE Scalar

#define ClientMessage_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,disconnect_res,msg.disconnect_res),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,get_properties_res,msg.get_properties_res),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,get_parameters_res,msg.get_parameters_res),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,fit_res,msg.fit_res),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,evaluate_res,msg.evaluate_res),   5)
#define ClientMessage_CALLBACK NULL
#define ClientMessage_DEFAULT NULL
#define ClientMessage_msg_disconnect_res_MSGTYPE ClientMessage_DisconnectRes
#define ClientMessage_msg_get_properties_res_MSGTYPE ClientMessage_GetPropertiesRes
#define ClientMessage_msg_get_parameters_res_MSGTYPE ClientMessage_GetParametersRes
#define ClientMessage_msg_fit_res_MSGTYPE ClientMessage_FitRes
#define ClientMessage_msg_evaluate_res_MSGTYPE ClientMessage_EvaluateRes

#define ClientMessage_DisconnectRes_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    reason,            1)
#define ClientMessage_DisconnectRes_CALLBACK NULL
#define ClientMessage_DisconnectRes_DEFAULT NULL

#define ClientMessage_GetPropertiesRes_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  status,            1) \
X(a, CALLBACK, REPEATED, MESSAGE,  properties,        2)
#define ClientMessage_GetPropertiesRes_CALLBACK pb_default_field_callback
#define ClientMessage_GetPropertiesRes_DEFAULT NULL
#define ClientMessage_GetPropertiesRes_status_MSGTYPE Status
#define ClientMessage_GetPropertiesRes_properties_MSGTYPE ClientMessage_GetPropertiesRes_PropertiesEntry

#define ClientMessage_GetPropertiesRes_PropertiesEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define ClientMessage_GetPropertiesRes_PropertiesEntry_CALLBACK pb_default_field_callback
#define ClientMessage_GetPropertiesRes_PropertiesEntry_DEFAULT NULL
#define ClientMessage_GetPropertiesRes_PropertiesEntry_value_MSGTYPE Scalar

#define ClientMessage_GetParametersRes_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  status,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  parameters,        2)
#define ClientMessage_GetParametersRes_CALLBACK NULL
#define ClientMessage_GetParametersRes_DEFAULT NULL
#define ClientMessage_GetParametersRes_status_MSGTYPE Status
#define ClientMessage_GetParametersRes_parameters_MSGTYPE Parameters

#define ClientMessage_FitRes_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  status,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  parameters,        2) \
X(a, STATIC,   SINGULAR, INT64,    num_examples,      3) \
X(a, CALLBACK, REPEATED, MESSAGE,  metrics,           4)
#define ClientMessage_FitRes_CALLBACK pb_default_field_callback
#define ClientMessage_FitRes_DEFAULT NULL
#define ClientMessage_FitRes_status_MSGTYPE Status
#define ClientMessage_FitRes_parameters_MSGTYPE Parameters
#define ClientMessage_FitRes_metrics_MSGTYPE ClientMessage_FitRes_MetricsEntry

#define ClientMessage_FitRes_MetricsEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define ClientMessage_FitRes_MetricsEntry_CALLBACK pb_default_field_callback
#define ClientMessage_FitRes_MetricsEntry_DEFAULT NULL
#define ClientMessage_FitRes_MetricsEntry_value_MSGTYPE Scalar

#define ClientMessage_EvaluateRes_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  status,            1) \
X(a, STATIC,   SINGULAR, FLOAT,    loss,              2) \
X(a, STATIC,   SINGULAR, INT64,    num_examples,      3) \
X(a, CALLBACK, REPEATED, MESSAGE,  metrics,           4)
#define ClientMessage_EvaluateRes_CALLBACK pb_default_field_callback
#define ClientMessage_EvaluateRes_DEFAULT NULL
#define ClientMessage_EvaluateRes_status_MSGTYPE Status
#define ClientMessage_EvaluateRes_metrics_MSGTYPE ClientMessage_EvaluateRes_MetricsEntry

#define ClientMessage_EvaluateRes_MetricsEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define ClientMessage_EvaluateRes_MetricsEntry_CALLBACK pb_default_field_callback
#define ClientMessage_EvaluateRes_MetricsEntry_DEFAULT NULL
#define ClientMessage_EvaluateRes_MetricsEntry_value_MSGTYPE Scalar

#define Scalar_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    DOUBLE,   (scalar,double_,scalar.double_),   1) \
X(a, STATIC,   ONEOF,    UINT64,   (scalar,uint64,scalar.uint64),   6) \
X(a, STATIC,   ONEOF,    SINT64,   (scalar,sint64,scalar.sint64),   8) \
X(a, STATIC,   ONEOF,    BOOL,     (scalar,bool_,scalar.bool_),  13) \
X(a, CALLBACK, ONEOF,    STRING,   (scalar,string,scalar.string),  14) \
X(a, CALLBACK, ONEOF,    BYTES,    (scalar,bytes,scalar.bytes),  15)
#define Scalar_CALLBACK pb_default_field_callback
#define Scalar_DEFAULT NULL

extern const pb_msgdesc_t Status_msg;
extern const pb_msgdesc_t Parameters_msg;
extern const pb_msgdesc_t ServerMessage_msg;
extern const pb_msgdesc_t ServerMessage_ReconnectIns_msg;
extern const pb_msgdesc_t ServerMessage_GetPropertiesIns_msg;
extern const pb_msgdesc_t ServerMessage_GetPropertiesIns_ConfigEntry_msg;
extern const pb_msgdesc_t ServerMessage_GetParametersIns_msg;
extern const pb_msgdesc_t ServerMessage_GetParametersIns_ConfigEntry_msg;
extern const pb_msgdesc_t ServerMessage_FitIns_msg;
extern const pb_msgdesc_t ServerMessage_FitIns_ConfigEntry_msg;
extern const pb_msgdesc_t ServerMessage_EvaluateIns_msg;
extern const pb_msgdesc_t ServerMessage_EvaluateIns_ConfigEntry_msg;
extern const pb_msgdesc_t ClientMessage_msg;
extern const pb_msgdesc_t ClientMessage_DisconnectRes_msg;
extern const pb_msgdesc_t ClientMessage_GetPropertiesRes_msg;
extern const pb_msgdesc_t ClientMessage_GetPropertiesRes_PropertiesEntry_msg;
extern const pb_msgdesc_t ClientMessage_GetParametersRes_msg;
extern const pb_msgdesc_t ClientMessage_FitRes_msg;
extern const pb_msgdesc_t ClientMessage_FitRes_MetricsEntry_msg;
extern const pb_msgdesc_t ClientMessage_EvaluateRes_msg;
extern const pb_msgdesc_t ClientMessage_EvaluateRes_MetricsEntry_msg;
extern const pb_msgdesc_t Scalar_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Status_fields &Status_msg
#define Parameters_fields &Parameters_msg
#define ServerMessage_fields &ServerMessage_msg
#define ServerMessage_ReconnectIns_fields &ServerMessage_ReconnectIns_msg
#define ServerMessage_GetPropertiesIns_fields &ServerMessage_GetPropertiesIns_msg
#define ServerMessage_GetPropertiesIns_ConfigEntry_fields &ServerMessage_GetPropertiesIns_ConfigEntry_msg
#define ServerMessage_GetParametersIns_fields &ServerMessage_GetParametersIns_msg
#define ServerMessage_GetParametersIns_ConfigEntry_fields &ServerMessage_GetParametersIns_ConfigEntry_msg
#define ServerMessage_FitIns_fields &ServerMessage_FitIns_msg
#define ServerMessage_FitIns_ConfigEntry_fields &ServerMessage_FitIns_ConfigEntry_msg
#define ServerMessage_EvaluateIns_fields &ServerMessage_EvaluateIns_msg
#define ServerMessage_EvaluateIns_ConfigEntry_fields &ServerMessage_EvaluateIns_ConfigEntry_msg
#define ClientMessage_fields &ClientMessage_msg
#define ClientMessage_DisconnectRes_fields &ClientMessage_DisconnectRes_msg
#define ClientMessage_GetPropertiesRes_fields &ClientMessage_GetPropertiesRes_msg
#define ClientMessage_GetPropertiesRes_PropertiesEntry_fields &ClientMessage_GetPropertiesRes_PropertiesEntry_msg
#define ClientMessage_GetParametersRes_fields &ClientMessage_GetParametersRes_msg
#define ClientMessage_FitRes_fields &ClientMessage_FitRes_msg
#define ClientMessage_FitRes_MetricsEntry_fields &ClientMessage_FitRes_MetricsEntry_msg
#define ClientMessage_EvaluateRes_fields &ClientMessage_EvaluateRes_msg
#define ClientMessage_EvaluateRes_MetricsEntry_fields &ClientMessage_EvaluateRes_MetricsEntry_msg
#define Scalar_fields &Scalar_msg

/* Maximum encoded size of messages (where known) */
/* Status_size depends on runtime parameters */
/* Parameters_size depends on runtime parameters */
/* ServerMessage_size depends on runtime parameters */
/* ServerMessage_GetPropertiesIns_size depends on runtime parameters */
/* ServerMessage_GetPropertiesIns_ConfigEntry_size depends on runtime parameters */
/* ServerMessage_GetParametersIns_size depends on runtime parameters */
/* ServerMessage_GetParametersIns_ConfigEntry_size depends on runtime parameters */
/* ServerMessage_FitIns_size depends on runtime parameters */
/* ServerMessage_FitIns_ConfigEntry_size depends on runtime parameters */
/* ServerMessage_EvaluateIns_size depends on runtime parameters */
/* ServerMessage_EvaluateIns_ConfigEntry_size depends on runtime parameters */
/* ClientMessage_size depends on runtime parameters */
/* ClientMessage_GetPropertiesRes_size depends on runtime parameters */
/* ClientMessage_GetPropertiesRes_PropertiesEntry_size depends on runtime parameters */
/* ClientMessage_GetParametersRes_size depends on runtime parameters */
/* ClientMessage_FitRes_size depends on runtime parameters */
/* ClientMessage_FitRes_MetricsEntry_size depends on runtime parameters */
/* ClientMessage_EvaluateRes_size depends on runtime parameters */
/* ClientMessage_EvaluateRes_MetricsEntry_size depends on runtime parameters */
/* Scalar_size depends on runtime parameters */
#define FLWR_PROTO_PROTO_TRANSPORT_PB_H_MAX_SIZE ServerMessage_ReconnectIns_size
#define ClientMessage_DisconnectRes_size 2
#define ServerMessage_ReconnectIns_size 11

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
