/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "transport.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Status, Status, AUTO)


PB_BIND(Parameters, Parameters, AUTO)


PB_BIND(ServerMessage, ServerMessage, AUTO)


PB_BIND(ServerMessage_ReconnectIns, ServerMessage_ReconnectIns, AUTO)


PB_BIND(ServerMessage_GetPropertiesIns, ServerMessage_GetPropertiesIns, AUTO)


PB_BIND(ServerMessage_GetPropertiesIns_ConfigEntry, ServerMessage_GetPropertiesIns_ConfigEntry, AUTO)


PB_BIND(ServerMessage_GetParametersIns, ServerMessage_GetParametersIns, AUTO)


PB_BIND(ServerMessage_GetParametersIns_ConfigEntry, ServerMessage_GetParametersIns_ConfigEntry, AUTO)


PB_BIND(ServerMessage_FitIns, ServerMessage_FitIns, AUTO)


PB_BIND(ServerMessage_FitIns_ConfigEntry, ServerMessage_FitIns_ConfigEntry, AUTO)


PB_BIND(ServerMessage_EvaluateIns, ServerMessage_EvaluateIns, AUTO)


PB_BIND(ServerMessage_EvaluateIns_ConfigEntry, ServerMessage_EvaluateIns_ConfigEntry, AUTO)


PB_BIND(ClientMessage, ClientMessage, AUTO)


PB_BIND(ClientMessage_DisconnectRes, ClientMessage_DisconnectRes, AUTO)


PB_BIND(ClientMessage_GetPropertiesRes, ClientMessage_GetPropertiesRes, AUTO)


PB_BIND(ClientMessage_GetPropertiesRes_PropertiesEntry, ClientMessage_GetPropertiesRes_PropertiesEntry, AUTO)


PB_BIND(ClientMessage_GetParametersRes, ClientMessage_GetParametersRes, AUTO)


PB_BIND(ClientMessage_FitRes, ClientMessage_FitRes, AUTO)


PB_BIND(ClientMessage_FitRes_MetricsEntry, ClientMessage_FitRes_MetricsEntry, AUTO)


PB_BIND(ClientMessage_EvaluateRes, ClientMessage_EvaluateRes, AUTO)


PB_BIND(ClientMessage_EvaluateRes_MetricsEntry, ClientMessage_EvaluateRes_MetricsEntry, AUTO)


PB_BIND(Scalar, Scalar, AUTO)







#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

